name: say-hello command runner
run-name: ${{ github.actor }} is doing smth suspicious
on: [push]
jobs:
  execute "make say-hello" command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Start"
      - run: make say-hello
      - run: echo "Job completed!"
